--------------------------------------------------------
--  File created - Friday-December-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PAYMENT" 
   (	"ID" NUMBER(10,0), 
	"DATETIME" DATE, 
	"MAINVALUE" FLOAT(126), 
	"TIPSVALUE" FLOAT(126)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table DELIVERYORDER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DELIVERYORDER" 
   (	"ID" NUMBER(10,0), 
	"CUSTOMERID" NUMBER(8,0), 
	"ZIPCODE" NUMBER(5,0), 
	"DELIVERID" NUMBER(8,0), 
	"DATETIME" DATE, 
	"ADDRESS" CHAR(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONENUM" CHAR(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDERSTATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVERYSTATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENTID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table DINEINORDER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DINEINORDER" 
   (	"ID" NUMBER(10,0), 
	"TABLEID" NUMBER(4,0), 
	"CUSTOMERID" NUMBER(8,0), 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DATETIME" DATE, 
	"PAYMENTID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table DININGTABLE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DININGTABLE" 
   (	"ID" NUMBER(4,0), 
	"ATTENDANTID" NUMBER(8,0), 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESERVATION" 
   (	"ID" NUMBER(4,0), 
	"CUSTOMERID" NUMBER(8,0), 
	"DATETIMEIN" DATE, 
	"DATETIMEOUT" DATE, 
	"TABLEID" NUMBER(4,0), 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for View CURRENTDATE_MONEY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."CURRENTDATE_MONEY" ("DAYDATE", "TOTALAMOUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT TO_CHAR(DATETIME, 'YYYY-MM-DD') CURRENT_DATE, SUM(MAINVALUE)
FROM PAYMENT
GROUP BY  TO_CHAR(DATETIME, 'YYYY-MM-DD')
ORDER BY TO_CHAR(DATETIME, 'YYYY-MM-DD')
;
--------------------------------------------------------
--  DDL for View DELIVERY_TIPS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."DELIVERY_TIPS" ("DELIVERY_ATTENDANTID", "TIPS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT DELIVERID, TIPSVALUE 
FROM
    (SELECT DELIVERID, SUM(TIPSVALUE) TIPSVALUE
     FROM DELIVERYORDER D INNER JOIN PAYMENT P ON P.ID = D.PAYMENTID
     GROUP BY DELIVERID
    )
;
--------------------------------------------------------
--  DDL for View DINEIN_TIPS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."DINEIN_TIPS" ("DINEIN_ATTENDANTID", "TIPS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT ATTENDANTID, TIPSVALUE
FROM
    (SELECT ATTENDANTID, SUM(TIPSVALUE) TIPSVALUE
     FROM (DINEINORDER D INNER JOIN DININGTABLE T ON D.TABLEID = T.ID) INNER JOIN PAYMENT P ON P.ID = D.PAYMENTID
     GROUP BY ATTENDANTID
     )
;
--------------------------------------------------------
--  DDL for View TABLE_AVAILABILITY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."TABLE_AVAILABILITY" ("CURRENTTIME", "TIMEIN", "TIMEOUT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT SYSDATE, DATETIMEIN, DATETIMEOUT
FROM RESERVATION 
WHERE RESERVATION.STATUS <> 'Cancel'
;
REM INSERTING into ADMIN.CURRENTDATE_MONEY
SET DEFINE OFF;
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-02',595);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-03',414);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-04',493);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-05',421);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-06',210);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-07',417);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-08',265);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-09',166);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-10',318);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-11',256);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-12',342);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-13',209);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-14',372);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-15',144);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-16',132);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-17',98);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-18',89);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-19',156);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-20',112);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-23',284);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-24',145);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-25',148);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-26',149);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-10-27',120);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-01',102);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-02',103);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-03',255);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-04',593);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-05',407);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-06',555);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-07',328);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-08',271);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-09',380);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-10',120);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-12',363);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-14',258);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-15',256);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-16',208);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-17',212);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-18',150);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-19',406);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-20',120);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-11-21',130);
Insert into ADMIN.CURRENTDATE_MONEY (DAYDATE,TOTALAMOUNT) values ('2021-12-19',111);
REM INSERTING into ADMIN.DELIVERY_TIPS
SET DEFINE OFF;
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (107,37);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (226,39);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (232,31);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (113,27);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (244,75);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (243,113);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (245,25);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (231,46);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (115,43);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (225,37);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (228,27);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (116,32);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (242,75);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (227,53);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (114,44);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (233,88);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (111,28);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (230,34);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (223,66);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (224,32);
Insert into ADMIN.DELIVERY_TIPS (DELIVERY_ATTENDANTID,TIPS) values (229,30);
REM INSERTING into ADMIN.DINEIN_TIPS
SET DEFINE OFF;
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (108,156);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (210,34);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (105,26);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (118,46);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (219,80);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (212,63);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (216,32);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (101,67);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (215,26);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (103,20);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (120,34);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (209,32);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (218,37);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (112,55);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (213,16);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (214,17);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (207,46);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (119,66);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (102,76);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (217,34);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (208,27);
Insert into ADMIN.DINEIN_TIPS (DINEIN_ATTENDANTID,TIPS) values (211,20);
REM INSERTING into ADMIN.TABLE_AVAILABILITY
SET DEFINE OFF;
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('01-NOV-21','DD-MON-RR'),to_date('01-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('01-NOV-21','DD-MON-RR'),to_date('01-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('02-DEC-21','DD-MON-RR'),to_date('02-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('02-NOV-21','DD-MON-RR'),to_date('02-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('02-NOV-21','DD-MON-RR'),to_date('02-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('03-NOV-21','DD-MON-RR'),to_date('03-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('03-NOV-21','DD-MON-RR'),to_date('03-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('04-NOV-21','DD-MON-RR'),to_date('04-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('04-NOV-21','DD-MON-RR'),to_date('05-DEC-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('05-NOV-21','DD-MON-RR'),to_date('05-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('05-NOV-21','DD-MON-RR'),to_date('05-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('06-NOV-21','DD-MON-RR'),to_date('06-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('07-NOV-21','DD-MON-RR'),to_date('07-NOV-21','DD-MON-RR'));
Insert into ADMIN.TABLE_AVAILABILITY (CURRENTTIME,TIMEIN,TIMEOUT) values (to_date('10-DEC-21','DD-MON-RR'),to_date('07-NOV-21','DD-MON-RR'),to_date('07-NOV-21','DD-MON-RR'));
